import BaseEndpoint from '../BaseEndpoint';
import { IOrderTemplateResult, IOrderTemplatesResult, IOrderTemplateResponseResult } from '../interfaces/OrderTemplate';
import { IWishListShare, IWishListRemoveItem, IOrderTemplateCreate, IOrderTemplateCreateAndAddItem, IOrderTemplateGet, IOrderTemplateList, IOrderTemplateAddItem, IOrderTemplateRemoveItem, IOrderTemplateAddPromotionCode, IOrderTemplateRemovePromotionCode, IOrderTemplateGetAppliedPromotionCode, IOrderTemplateItemEdit, IOrderTemplateEdit, IOrderTemplateEditFrequency, IOrderTemplateEditSchedule, IOrderTemplateCancelOrderTemplate, IOrderTemplateUpdateShipping } from '../interfaces/requests/OrderTemplate';
import { IHeaders } from '../SDKScope';
export default class OrderTemplate extends BaseEndpoint {
    create(params: IOrderTemplateCreate, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    addItem(params: IOrderTemplateAddItem, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    createAndAddItem(params: IOrderTemplateCreateAndAddItem, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    removeItem(params: IOrderTemplateRemoveItem, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    addPromotionCode(params: IOrderTemplateAddPromotionCode, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    removePromotionCode(params: IOrderTemplateRemovePromotionCode, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    getAppliedPromotionCodes(params: IOrderTemplateGet, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    getPromotionProducts(params: IOrderTemplateGetAppliedPromotionCode, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    removePromotionItems(params: IOrderTemplateGetAppliedPromotionCode, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    list(params: IOrderTemplateList, headers?: IHeaders, source?: any): Promise<IOrderTemplatesResult>;
    createWishlist(params: IOrderTemplateCreate, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    addWishlistItem(params: IOrderTemplateAddItem, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    addWishlistItemAndGetWishList(params: IOrderTemplateAddItem, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    removeWishlistItem(params: IWishListRemoveItem, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    removeWishlistItemAndGetWishList(params: IWishListRemoveItem, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    shareWishlist(params: IWishListShare, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    getWishlists(headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    getWishListItems(headers?: IHeaders, source?: any): Promise<IOrderTemplatesResult>;
    getOrderTemplateItems(params: IOrderTemplateGet, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    getOrderTemplateDetails(params: IOrderTemplateGet, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    updateOrderTemplateShipping(params: IOrderTemplateUpdateShipping, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    updateOrderTemplateBilling(params: IOrderTemplateUpdateShipping, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    getCancellationReasonTypeOptions(headers?: IHeaders, source?: any): Promise<IOrderTemplatesResult>;
    getFrequencyTermOptions(headers?: IHeaders, source?: any): Promise<IOrderTemplatesResult>;
    getScheduleDateChangeReasonTypeOptions(headers?: IHeaders, source?: any): Promise<IOrderTemplatesResult>;
    editOrderTemplateItem(params: IOrderTemplateItemEdit, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    editOrderTemplate(params: IOrderTemplateEdit, headers?: IHeaders, source?: any): Promise<IOrderTemplateResponseResult>;
    updateOrderTemplateFrequency(params: IOrderTemplateEditFrequency, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    updateOrderTemplateSchedule(params: IOrderTemplateEditSchedule, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
    cancelOrderTemplate(params: IOrderTemplateCancelOrderTemplate, headers?: IHeaders, source?: any): Promise<IOrderTemplateResult>;
}
